name: CI

on:
  push:
    # tags: v*.*
    branch: master
    
jobs:
  build_on_mac:
    runs-on: macOS-latest
    steps:
    - name: Setup 
      uses: actions/checkout@v2

    - name: Setup Python 3.7.6
      uses: actions/setup-python@v1.2.0
      with:
        python-version: 3.7.6

    - name: Install Package
      run: |
           ls -la
           python -m pip install --upgrade pip 
           pip install pyinstaller
           ls
           pip install -r ./requirements.txt

    - name: Build with Pyinstaller
      run: pyinstaller --onefile Itokake.py --add-data static:static --add-data templates:templateselec
      
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Setup Electron and Build with Electron_Builder
      run: cp dist/Itokake Electron_Build/py_app/Itokake
           && cd Electron_Build && npm install && node build-mac.js

    - name: Release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        title: "Development Build"
        files: |
          Electron_Build/build/mac/*.zip

  build_on_windows:
    runs-on: windows-latest
    steps:
    - name: Setup 
      uses: actions/checkout@v2

    - name: Setup Python 3.7.6
      uses: actions/setup-python@v1.2.0
      with:
        python-version: 3.7.6

    - name: Install Package
      run: |
           ls -la
           python -m pip install --upgrade pip 
           pip install pyinstaller
           ls
           pip install -r ./requirements.txt

    - name: Build with Pyinstaller
      run: pyinstaller --onefile Itokake.py --add-data static:static --add-data templates:templateselec
      
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Setup Electron and Build with Electron_Builder
      run: cp dist/Itokake.exe Electron_Build/py_app/Itokake.exe
           && cd Electron_Build && npm install && node build-win.js

    - name: Release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        title: "Development Build"
        files: |
          Electron_Build/build/win/*.zip