name: CI

on:
  push:
    # tags: v*.*
    branch: master
    
jobs:
  build_on_mac:
    runs-on: macOS-latest
    steps:
    - name: Setup 
      uses: actions/checkout@v2

    - name: Setup Python 3.7.6
      uses: actions/setup-python@v1.2.0
      with:
        python-version: 3.7.6

    - name: Install Package
      run: |
           ls -la
           python -m pip install --upgrade pip 
           pip install pyinstaller
           ls
           pip install -r ./requirements.txt

    - name: Build with Pyinstaller
      run: pyinstaller --onefile Itokake.py --add-data static:static --add-data templates:templateselec
      
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Setup Electron and Build with Electron_Builder
      run: cp dist/Itokake Electron_Build/py_app/Itokake
           && cd Electron_Build && npm install && node build-mac.js

    - name: Create release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          Electron_Build/build/mac/**
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
