name: CI

on:
  push:
    branches: master
    
jobs:
  build:
    runs-on: macOS-latest
    steps:
      uses: actions/checkout@v2

    - name: Setup Python 3.7.6
      uses: actions/setup-python@v1.2.0
      with:
        python-version: 3.7.6

    - name: Install Package
      run: |
           ls -la
           python -m pip install --upgrade pip 
           pip install pyinstaller
           ls
           pip install -r ./requirements.txt

    - name: Build with Pyinstaller
      run: pyinstaller --onefile Itokake.py --add-data static;static --add-data templates;templateselec
      
    - name: Setup Node.js
      uses: actions/setup-node@v1.1.0

    - name: Setup Electron
      run: cp dist/Itokake Electron_Build/py_app/Itokake 
           && cd Electron_Build && node build-mac.js && ls

    # - uses: actions/checkout@master
    # - name: copy file via ssh password
    #   uses: appleboy/scp-action@master
    #   with:
    #     host: ${{ secrets.HOST }}
    #     username: ${{ secrets.USERNAME }}
    #     key: ${{ secrets.KEY }}
    #     port: ${{ secrets.PORT }}
    #     source: ""
    #     target: "test"
